bizbiz/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('pages.urls')),
    path('dashboard/',include('dashboard.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bizbizerp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('django_ledger.urls', namespace='django_ledger')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
app_name = "dashboard"
urlpatterns = [
    path('',views.DashboardView.as_view(),name="index")
]

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Homepage.as_view(),name="homepage"),
]

django_ledger/models/accounts.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""
from typing import Union
from uuid import uuid4

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.utils.translation import gettext_lazy as _

from django_ledger.io.roles import ACCOUNT_ROLES, BS_ROLES, GROUP_INVOICE, GROUP_BILL
from django_ledger.models.mixins import CreateUpdateMixIn, NodeTreeMixIn

DEBIT = 'debit'
CREDIT = 'credit'


class AccountModelQuerySet(models.QuerySet):

    def active(self):
        return self.filter(active=True)

    def with_roles(self, roles: Union[list, str]):
        if isinstance(roles, str):
            roles = [roles]
        return self.filter(role__in=roles)


class AccountModelManager(models.Manager):

    def get_queryset(self):
        return AccountModelQuerySet(self.model, using=self._db)

    def for_entity(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.get_queryset()
        qs = qs.filter(
            Q(coa__entity__slug__exact=entity_slug) &
            (
                    Q(coa__entity__admin=user_model) |
                    Q(coa__entity__managers__in=[user_model])
            )
        ).order_by('code')
        if coa_slug:
            qs = qs.filter(coa__slug__iexact=coa_slug)
        return qs

    def with_roles(self, roles: Union[list, str], entity_slug: str, user_model):
        if isinstance(roles, str):
            roles = [roles]
        qs = self.for_entity(entity_slug=entity_slug, user_model=user_model)
        return qs.filter(role__in=roles)

    def with_roles_available(self, roles: Union[list, str], entity_slug: str, user_model):
        if isinstance(roles, str):
            roles = [roles]
        qs = self.for_entity_available(entity_slug=entity_slug, user_model=user_model)
        return qs.filter(role__in=roles)

    def for_entity_available(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(
            active=True,
            locked=False
        )

    def for_invoice(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity_available(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(role__in=GROUP_INVOICE)

    def for_bill(self, user_model, entity_slug: str, coa_slug: str = None):
        qs = self.for_entity_available(
            user_model=user_model,
            entity_slug=entity_slug,
            coa_slug=coa_slug)
        return qs.filter(role__in=GROUP_BILL)


class AccountModelAbstract(NodeTreeMixIn, CreateUpdateMixIn):
    """
    Djetler's Base Account Model Abstract
    """
    BALANCE_TYPE = [
        (CREDIT, _('Credit')),
        (DEBIT, _('Debit'))
    ]

    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    code = models.CharField(max_length=10, verbose_name=_('Account Code'))
    name = models.CharField(max_length=100, verbose_name=_('Account Name'))
    role = models.CharField(max_length=25, choices=ACCOUNT_ROLES, verbose_name=_('Account Role'))
    balance_type = models.CharField(max_length=6, choices=BALANCE_TYPE, verbose_name=_('Account Balance Type'))
    locked = models.BooleanField(default=False, verbose_name=_('Locked'))
    active = models.BooleanField(default=False, verbose_name=_('Active'))
    coa = models.ForeignKey('django_ledger.ChartOfAccountModel',
                            on_delete=models.CASCADE,
                            verbose_name=_('Chart of Accounts'),
                            related_name='accounts')
    on_coa = AccountModelManager()

    class Meta:
        abstract = True
        ordering = ['-created']
        verbose_name = _('Account')
        verbose_name_plural = _('Accounts')
        unique_together = [
            ('coa', 'code')
        ]
        indexes = [
            models.Index(fields=['role']),
            models.Index(fields=['balance_type']),
            models.Index(fields=['active']),
            models.Index(fields=['coa']),
            models.Index(fields=['role', 'balance_type', 'active']),
        ]

    def __str__(self):
        return '{x1} - {x5}: {x2} ({x3}/{x4})'.format(x1=self.role_bs.upper(),
                                                      x2=self.name,
                                                      # pylint: disable=no-member
                                                      x3=self.role.upper(),
                                                      x4=self.balance_type,
                                                      x5=self.code)

    @property
    def role_bs(self):
        return BS_ROLES.get(self.role)

    def is_debit(self):
        return self.balance_type == DEBIT

    def is_credit(self):
        return self.balance_type == CREDIT

    def clean(self):
        # pylint: disable=unsupported-membership-test
        if ' ' in self.code:
            raise ValidationError(_('Account code must not contain spaces'))


class AccountModel(AccountModelAbstract):
    """
    Base Account Model from Account Model Abstract Class
    """

django_ledger/models/journalentry.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""
from decimal import Decimal
from uuid import uuid4

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q, Sum, QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from django_ledger.models import CreateUpdateMixIn, NodeTreeMixIn


class JournalEntryModelQuerySet(QuerySet):

    def create(self, verify_on_save: bool = False, **kwargs):
        obj = self.model(**kwargs)
        self._for_write = True

        # verify_on_save option avoids additional queries to validate that JE has CR/DB balanced.
        # New JEs using the create() method don't have TXS to validate.
        # therefore, it is not necessary to query DB to balance TXS.

        obj.save(force_insert=True, using=self.db, verify_txs=verify_on_save)
        return obj


class JournalEntryModelManager(models.Manager):

    def get_queryset(self):
        return JournalEntryModelQuerySet(
            self.model,
            using=self._db
        )

    def for_entity(self, entity_slug: str, user_model):
        return self.get_queryset().filter(
            Q(ledger__entity__slug__iexact=entity_slug) &
            (
                    Q(ledger__entity__admin=user_model) |
                    Q(ledger__entity__managers__in=[user_model])
            )

        )

    def for_ledger(self, ledger_pk: str, entity_slug: str, user_model):
        qs = self.for_entity(entity_slug=entity_slug, user_model=user_model)
        return qs.filter(ledger__uuid__exact=ledger_pk)


class JournalEntryModelAbstract(NodeTreeMixIn, CreateUpdateMixIn):
    ACTIVITY_IGNORE = ['all']
    ACTIVITIES = [
        ('op', _('Operating')),
        ('fin', _('Financing')),
        ('inv', _('Investing')),
        ('other', _('Other')),
    ]

    ACTIVITY_ALLOWS = [a[0] for a in ACTIVITIES]
    parent = models.ForeignKey('self',
                               blank=True,
                               null=True,
                               verbose_name=_('Parent Journal Entry'),
                               related_name='children',
                               on_delete=models.CASCADE)

    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    date = models.DateField(verbose_name=_('Date'))
    description = models.CharField(max_length=70, blank=True, null=True, verbose_name=_('Description'))
    entity_unit = models.ForeignKey('django_ledger.EntityUnitModel',
                                    on_delete=models.PROTECT,
                                    blank=True,
                                    null=True,
                                    verbose_name=_('Associated Entity Unit'))
    activity = models.CharField(choices=ACTIVITIES, max_length=5, verbose_name=_('Activity'))
    origin = models.CharField(max_length=30, blank=True, null=True, verbose_name=_('Origin'))
    posted = models.BooleanField(default=False, verbose_name=_('Posted'))
    locked = models.BooleanField(default=False, verbose_name=_('Locked'))
    ledger = models.ForeignKey('django_ledger.LedgerModel',
                               verbose_name=_('Ledger'),
                               related_name='journal_entries',
                               on_delete=models.CASCADE)

    on_coa = JournalEntryModelManager()
    objects = JournalEntryModelManager()

    class Meta:
        abstract = True
        ordering = ['-created']
        verbose_name = _('Journal Entry')
        verbose_name_plural = _('Journal Entries')
        indexes = [
            models.Index(fields=['date']),
            models.Index(fields=['activity']),
            models.Index(fields=['parent']),
            models.Index(fields=['entity_unit']),
            models.Index(fields=['ledger', 'posted']),
            models.Index(fields=['locked']),
        ]

    def __str__(self):
        return 'JE ID: {x1} - Desc: {x2}'.format(x1=self.pk, x2=self.description)

    def get_absolute_url(self):
        return reverse('django_ledger:je-detail',
                       kwargs={
                           'je_pk': self.id,
                           'ledger_pk': self.ledger_id,
                           # pylint: disable=no-member
                           'entity_slug': self.ledger.entity.slug
                       })

    def get_balances(self):
        txs_qs = self.txs.order_by('tx_type').values('tx_type').annotate(
            tx_type_total=Sum('amount'))
        txs_idx = {
            i['tx_type']: i['tx_type_total'] for i in txs_qs
        }
        balances = {
            'credit': txs_idx.get('credit', Decimal('0.00')),
            'debit': txs_idx.get('debit', Decimal('0.00'))
        }
        return balances

    def je_is_valid(self):
        balances = self.get_balances()
        return balances['credit'] == balances['debit']

    def clean(self, verify_txs: bool = True):
        check1 = 'Debits and credits do not match.'
        if verify_txs:
            if not self.je_is_valid():
                raise ValidationError(check1)

    def mark_as_posted(self, commit: bool = False):
        if not self.posted:
            self.posted = True
            if commit:
                self.save(update_fields=[
                    'posted',
                    'updated'
                ])

    def mark_as_locked(self, commit: bool = False):
        if not self.locked:
            self.locked = True
            if commit:
                self.save(update_fields=[
                    'locked',
                    'updated'
                ])

    def mark_as_unlocked(self, commit: bool = False):
        if self.locked:
            self.locked = False
            if commit:
                self.save(update_fields=[
                    'locked',
                    'updated'
                ])

    def save(self, verify_txs: bool = True, *args, **kwargs):
        try:
            self.clean(verify_txs=verify_txs)
        except ValidationError as e:
            self.txs.all().delete()
            raise ValidationError(f'Something went wrong cleaning journal entry ID: {self.uuid}: {e}')
        super().save(*args, **kwargs)


class JournalEntryModel(JournalEntryModelAbstract):
    """
    Journal Entry Model Base Class From Abstract
    """

django_ledger/forms/account.py
from django.forms import TextInput, Select, ModelForm

from django_ledger.models.accounts import AccountModel
from django_ledger.settings import DJANGO_LEDGER_FORM_INPUT_CLASSES


class AccountModelCreateForm(ModelForm):
    def __init__(self, entity_slug, user_model, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ENTITY_SLUG = entity_slug
        self.USER_MODEL = user_model

    class Meta:
        model = AccountModel
        fields = [
            'code',
            'name',
            'role',
            'balance_type',
        ]
        widgets = {
            'code': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'name': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'role': Select(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'balance_type': Select(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
        }


class AccountModelCreateChildForm(AccountModelCreateForm):
    class Meta:
        model = AccountModel
        fields = [
            'code',
            'name',
            'balance_type',
        ]
        widgets = {
            'code': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'name': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'balance_type': Select(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
        }


class AccountModelUpdateForm(ModelForm):

    def __init__(self, entity_slug, user_model, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ENTITY_SLUG = entity_slug
        self.USER_MODEL = user_model
        self.PARENT_ACCOUNT: AccountModel = self.instance.parent

        if self.PARENT_ACCOUNT:
            self.fields['parent'].queryset = AccountModel.on_coa.with_roles_available(
                entity_slug=self.ENTITY_SLUG,
                user_model=self.USER_MODEL,
                roles=[self.PARENT_ACCOUNT.role]
            )
        else:
            self.fields['parent'].queryset = AccountModel.on_coa.for_entity_available(
                user_model=self.USER_MODEL,
                entity_slug=self.ENTITY_SLUG,
            )

    class Meta:
        model = AccountModel
        fields = [
            'parent',
            'code',
            'name',
            'locked',
            'active'
        ]
        widgets = {
            'parent': Select(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'code': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'name': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
        }

django_ledger/templates/django_ledger/tags/accounts_table.html
{% load i18n %}
{% load django_ledger %}

<div class="table-container">
    <table class="table is-fullwidth is-striped is-narrow django-ledger-table-bottom-margin-75">
        <thead>
            {% if title %}
                <tr>
                    <td><h2 class="is-size-3 has-text-weight-light">{{ title }}</h2></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            {% endif %}
            <tr>
                <th>{% trans 'Role' %}</th>
                <th>{% trans 'Parent' %}</th>
                <th>{% trans 'Code' %}</th>
                <th>{% trans 'Account Name' %}</th>
                <th>{% trans 'Balance Type' %}</th>
                <th>{% trans 'Active' %}</th>
                <th>{% trans 'Locked' %}</th>
                <th>{% trans 'Actions' %}</th>
            </tr>
        </thead>

        <tbody>
            {% for account in accounts %}
                <tr>
                    <td>{{ account.get_role_display }}</td>
                    <td>{{ account.parent.code }}</td>
                    <td>{{ account.code }}</td>
                    <td>{{ account.name }}</td>
                    <td class="has-text-centered">
                        {% if account.is_debit %}
                            <span class="icon has-text-info-dark">{% icon 'bi:arrow-bar-down' 24 %}</span>
                        {% elif account.is_credit %}
                            <span class="icon has-text-warning-dark">{% icon 'bi:arrow-bar-up' 24 %}</span>
                        {% endif %}
                    </td>
                    <td class="has-text-centered">
                        {% if account.active %}
                            <span class="icon has-text-success-dark">
                                {% icon 'ant-design:check-circle-filled' 24 %}
                            </span>
                        {% endif %}
                    </td>
                    <td class="has-text-centered">
                        {% if account.locked %}
                            <span class="icon has-text-success-dark">
                                {% icon 'bi:lock-fill' 24 %}
                            </span>
                        {% elif not account.locked %}
                            <span class="icon has-text-danger-dark">
                                {% icon 'bx:bx-lock-open-alt' 24 %}
                            </span>
                        {% endif %}
                    </td>
                    <td>
                        <div class="dropdown is-right is-hoverable" id="account-action-{{ account.uuid }}">
                            <div class="dropdown-trigger">
                                <button class="button is-small is-rounded is-outlined"
                                        aria-haspopup="true"
                                        aria-controls="dropdown-menu">
                                    <span>Actions</span>
                                    <span class="icon is-small">{% icon 'bi:arrow-down' 24 %}</span>
                                </button>
                            </div>
                            <div class="dropdown-menu" id="dropdown-menu-{{ account.uuid }}" role="menu">
                                <div class="dropdown-content">
                                    <a href="{% url 'django_ledger:account-detail' entity_slug=entity_slug account_pk=account.uuid %}"
                                       class="dropdown-item has-text-success">{% trans 'Detail' %}</a>
                                    <a href="{% url 'django_ledger:account-update' entity_slug=entity_slug account_pk=account.uuid %}"
                                       class="dropdown-item has-text-warning">{% trans 'Update' %}</a>
                                    <a href="{% url 'django_ledger:account-create-child' entity_slug=entity_slug parent_account_pk=account.uuid %}"
                                       class="dropdown-item has-text-info">{% trans 'Create Child Account' %}</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
    </table>
</div>

django_ledger/templates/django_ledger/tags/bill_item_formset.html
{% load trans from i18n %}
{% load django_ledger %}

<form action="{% url 'django_ledger:bill-update-items' entity_slug=entity_slug bill_pk=bill_pk %}"
      method="post">
    <div class="columns is-multiline">
        <div class="column is-12">
            <h1 class="is-size-1">{% trans 'Bill Items' %}</h1>
        </div>
        <div class="column is-12">
            <div class="table-container">
                {% csrf_token %}
                {{ item_formset.non_form_errors }}
                {{ item_formset.management_form }}
                <table class="table is-fullwidth is-narrow is-striped is-bordered">
                    <thead>
                    <tr>
                        <th>{% trans 'Item' %}</th>
                        <th>{% trans 'PO Qty' %}</th>
                        <th>{% trans 'PO Amount' %}</th>
                        <th>{% trans 'Quantity' %}</th>
                        <th>{% trans 'Unit Cost' %}</th>
                        <th>{% trans 'Unit' %}</th>
                        <th>{% trans 'Total' %}</th>
                        <th>{% trans 'Delete' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for f in item_formset %}
                        <tr>
                            <td>
                                {% for hidden_field in f.hidden_fields %}
                                    {{ hidden_field }}
                                {% endfor %}
                                {{ f.item_model }}
                                {% if f.errors %}
                                    <span class="has-text-danger">{{ f.errors }}</span>
                                {% endif %}
                            </td>
                            <td>{% if f.instance.po_quantity %}{{ f.instance.po_quantity }}{% endif %}</td>
                            <td>{% if f.instance.po_total_amount %}{% currency_symbol %}
                                {{ f.instance.po_total_amount | currency_format }}
                                <a class="button is-small is-info is-outlined"
                                   href="{% url 'django_ledger:po-detail' entity_slug=entity_slug po_pk=f.instance.po_model_id %}">
                                    {% trans 'View PO' %}
                                </a>{% endif %}</td>
                            <td id="{{ f.instance.html_id_quantity }}">{{ f.quantity }}</td>
                            <td id="{{ f.instance.html_id_unit_cost }}">{{ f.unit_cost }}</td>
                            <td>{{ f.entity_unit }}</td>
                            <td class="has-text-right" id="{{ f.instance.html_id_total_amount }}">
                                {% currency_symbol %}{{ f.instance.total_amount | currency_format }}</td>
                            <td class="has-text-centered">
                                {% if item_formset.can_delete %}
                                    {{ f.DELETE }}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th class="has-text-right">{% trans 'Total' %}</th>
                        <th class="has-text-right">{% currency_symbol %}{{ total_amount_due | currency_format }}</th>
                        <th></th>
                    </tr>
                    </tfoot>

                </table>
            </div>
        </div>
        <div class="column is-12">
            {% if not item_formset.has_po %}
                <a href="{% url 'django_ledger:product-create' entity_slug=entity_slug %}"
                   class="button is-primary">{% trans 'New Item' %}</a>
            {% endif %}
            <button class="button is-primary">{% trans 'Save' %}</button>
        </div>
    </div>
</form>

django_ledger/templates/django_ledger/tags/breadcrumbs.html
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li>
            <a href="{% url 'django_ledger:dashboard' %}">
        <span class="icon is-small">
          <i class="mdi mdi-view-dashboard-variant" aria-hidden="true"></i>
        </span>
                <span>Dashboard</span>
            </a>
        </li>

        {% if entity_slug %}
            <li>
                <a href="#">
        <span class="icon is-small">
          <i class="fas fa-book" aria-hidden="true"></i>
        </span>
                    <span>Documentation</span>
                </a>
            </li>
            <li>
                <a href="#">
        <span class="icon is-small">
          <i class="fas fa-puzzle-piece" aria-hidden="true"></i>
        </span>
                    <span>Components</span>
                </a>
            </li>
            <li class="is-active">
                <a href="#">
        <span class="icon is-small">
          <i class="fas fa-thumbs-up" aria-hidden="true"></i>
        </span>
                    <span>Breadcrumb</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

django_ledger/templates/django_ledger/tags/icon.html
<i class="iconify djl-icon-{{ size }}" data-icon="{{ icon }}" data-toggle="true"></i>

django_ledger/templates/django_ledger/tags/jes_table.html
{% load django_ledger %}

<div class="table-container">
    <table class="table is-fullwidth is-narrow is-striped django-ledger-table-bottom-margin-150">
        <thead>
        <tr class="has-text-centered">
            <th>Description</th>
            <th>Activity</th>
            <th>JE Date</th>
            <th>Posted</th>
            <th>Locked</th>
            <th>Created</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for je in jes %}
            <tr class="has-text-centered">
                <td>{{ je.description }}</td>
                <td>{{ je.get_activity_display }}</td>
                <td>{{ je.date }}</td>
                <td>
                    {% if je.posted %}
                        <span class="icon has-text-success">{% icon 'ant-design:check-circle-filled' 24 %}</span>
                    {% else %}
                        <span class="icon is-small has-text-danger">{% icon 'maki:roadblock-11' 24 %}</span>
                    {% endif %}
                </td>
                <td>
                    {% if je.locked %}
                        <span class="icon has-text-success-dark">
                            {% icon 'bi:lock-fill' 24 %}
                        </span>
                    {% else %}
                        <span class="icon has-text-danger-dark">
                            {% icon 'bx:bx-lock-open-alt' 24 %}
                        </span>
                    {% endif %}
                </td>
                <td>{{ je.created | timesince }}</td>
                <td>
                    <div class="dropdown is-right is-hoverable"
                         id="je-action-{{ je.uuid }}">
                        <div class="dropdown-trigger">
                            <button class="button is-small is-rounded is-outlined is-dark"
                                    aria-haspopup="true"
                                    aria-controls="dropdown-menu">
                                <span>Actions</span>
                                <span class="icon is-small">
                                        {% icon 'bi:arrow-down' 24 %}
                                      </span>
                            </button>
                        </div>

                        <div class="dropdown-menu"
                             id="dropdown-menu-{{ je.uuid }}"
                             role="menu">
                            <div class="dropdown-content">
                                {% if not je.posted %}
                                    <a class="dropdown-item"
                                       href="{% url 'django_ledger:je-mark-as-posted' entity_slug=entity_slug ledger_pk=ledger_pk je_pk=je.uuid %}?next={{ next_url }}">
                                        Post</a>
                                {% endif %}
                                {% if not je.locked %}
                                    <a class="dropdown-item"
                                       href="{% url 'django_ledger:je-mark-as-locked' entity_slug=entity_slug ledger_pk=ledger_pk je_pk=je.uuid %}?next={{ next_url }}">
                                        Lock</a>
                                {% else %}
                                    <a class="dropdown-item"
                                       href="{% url 'django_ledger:je-mark-as-unlocked' entity_slug=entity_slug ledger_pk=ledger_pk je_pk=je.uuid %}?next={{ next_url }}">
                                        UnLock</a>
                                {% endif %}
                                <a class="dropdown-item"
                                   href="{% url 'django_ledger:je-update' entity_slug=entity_slug ledger_pk=ledger_pk je_pk=je.uuid %}">Edit</a>
                                <a class="dropdown-item"
                                   href="{% url 'django_ledger:je-detail' entity_slug=entity_slug ledger_pk=ledger_pk je_pk=je.uuid %}">View</a>
                                <a class="dropdown-item"
                                   href="{% url 'django_ledger:txs-journal-entry' entity_slug=entity_slug ledger_pk=ledger_pk je_pk=je.uuid %}">Txs</a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>