bizbiz/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('pages.urls')),
    path('dashboard/',include('dashboard.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bizbizerp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('',include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('django_ledger.urls', namespace='django_ledger')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.Homepage.as_view(),name="homepage"),
]

django_ledger/models/invoice.py
"""
Django Ledger created by Miguel Sanda <msanda@arrobalytics.com>.
Copyright© EDMA Group Inc licensed under the GPLv3 Agreement.

Contributions to this module:
Miguel Sanda <msanda@arrobalytics.com>
"""
from decimal import Decimal
from random import choices
from string import ascii_uppercase, digits
from uuid import uuid4

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q, Sum, Count
from django.db.models.signals import post_delete
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from django_ledger.models import LazyLoader
from django_ledger.models.entity import EntityModel
from django_ledger.models.mixins import CreateUpdateMixIn, LedgerPlugInMixIn, MarkdownNotesMixIn

UserModel = get_user_model()

lazy_loader = LazyLoader()

INVOICE_NUMBER_CHARS = ascii_uppercase + digits


def generate_invoice_number(length: int = 10, prefix: bool = True) -> str:
    """
    A function that generates a random bill identifier for new bill models.
    :param prefix:
    :param length: The length of the bill number.
    :return: A string representing a random bill identifier.
    """
    invoice_number = ''.join(choices(INVOICE_NUMBER_CHARS, k=length))
    if prefix:
        invoice_number = 'I-' + invoice_number
    return invoice_number


class InvoiceModelManager(models.Manager):

    def for_entity(self, entity_slug, user_model):
        qs = self.get_queryset().filter(
            Q(ledger__entity__admin=user_model) |
            Q(ledger__entity__managers__in=[user_model])
        )
        if isinstance(entity_slug, EntityModel):
            return qs.filter(ledger__entity=entity_slug)
        elif isinstance(entity_slug, str):
            return qs.filter(ledger__entity__slug__exact=entity_slug)

    def for_entity_unpaid(self, entity_slug, user_model):
        qs = self.for_entity(entity_slug=entity_slug, user_model=user_model)
        return qs.filter(paid=False)


class InvoiceModelAbstract(LedgerPlugInMixIn,
                           MarkdownNotesMixIn,
                           CreateUpdateMixIn):
    IS_DEBIT_BALANCE = True
    REL_NAME_PREFIX = 'invoice'

    INVOICE_STATUS_DRAFT = 'draft'
    INVOICE_STATUS_REVIEW = 'in_review'
    INVOICE_STATUS_APPROVED = 'approved'
    INVOICE_STATUS_CANCELED = 'canceled'

    INVOICE_STATUS = [
        (INVOICE_STATUS_DRAFT, _('Draft')),
        (INVOICE_STATUS_REVIEW, _('In Review')),
        (INVOICE_STATUS_APPROVED, _('Approved')),
        (INVOICE_STATUS_CANCELED, _('Canceled'))
    ]

    uuid = models.UUIDField(default=uuid4, editable=False, primary_key=True)
    invoice_number = models.SlugField(max_length=20, unique=True, verbose_name=_('Invoice Number'))
    invoice_status = models.CharField(max_length=10, choices=INVOICE_STATUS, default=INVOICE_STATUS[0][0],
                                      verbose_name=_('Invoice Status'))
    customer = models.ForeignKey('django_ledger.CustomerModel',
                                 on_delete=models.PROTECT,
                                 verbose_name=_('Customer'))

    cash_account = models.ForeignKey('django_ledger.AccountModel',
                                     on_delete=models.PROTECT,
                                     verbose_name=_('Cash Account'),
                                     related_name=f'{REL_NAME_PREFIX}_cash_account')
    prepaid_account = models.ForeignKey('django_ledger.AccountModel',
                                        on_delete=models.PROTECT,
                                        verbose_name=_('Prepaid Account'),
                                        related_name=f'{REL_NAME_PREFIX}_prepaid_account')
    unearned_account = models.ForeignKey('django_ledger.AccountModel',
                                         on_delete=models.PROTECT,
                                         verbose_name=_('Unearned Account'),
                                         related_name=f'{REL_NAME_PREFIX}_unearned_account')

    additional_info = models.JSONField(default=dict, verbose_name=_('Invoice Additional Info'))
    invoice_items = models.ManyToManyField('django_ledger.ItemModel',
                                           through='django_ledger.ItemThroughModel',
                                           through_fields=('invoice_model', 'item_model'),
                                           verbose_name=_('Invoice Items'))

    objects = InvoiceModelManager()

    class Meta:
        abstract = True
        ordering = ['-updated']
        verbose_name = _('Invoice')
        verbose_name_plural = _('Invoices')
        indexes = [
            models.Index(fields=['cash_account']),
            models.Index(fields=['prepaid_account']),
            models.Index(fields=['unearned_account']),
            models.Index(fields=['date']),
            models.Index(fields=['due_date']),
            models.Index(fields=['paid']),
        ]

    def __str__(self):
        return f'Invoice: {self.invoice_number}'

    def configure(self,
                  entity_slug: str or EntityModel,
                  user_model: UserModel,
                  post_ledger: bool = False):

        if isinstance(entity_slug, str):
            entity_qs = EntityModel.objects.for_user(
                user_model=user_model)
            entity_model: EntityModel = get_object_or_404(entity_qs, slug__exact=entity_slug)
        elif isinstance(entity_slug, EntityModel):
            entity_model = entity_slug
        else:
            raise ValidationError('entity_slug must be an instance of str or EntityModel')

        if not self.invoice_number:
            self.invoice_number = generate_invoice_number()

        LedgerModel = lazy_loader.get_ledger_model()

        ledger_model = LedgerModel.objects.create(
            entity=entity_model,
            posted=post_ledger,
            name=f'Invoice {self.invoice_number}',
        )
        ledger_model.clean()
        self.ledger = ledger_model
        return ledger_model, self

    def get_html_id(self):
        return f'djl-{self.REL_NAME_PREFIX}-{self.uuid}'

    def get_html_amount_due_id(self):
        return f'djl-{self.REL_NAME_PREFIX}-{self.uuid}-amount-due'

    def get_html_amount_paid_id(self):
        return f'djl-{self.REL_NAME_PREFIX}-{self.uuid}-amount-paid'

    def get_html_form_name(self):
        return f'djl-form-{self.REL_NAME_PREFIX}-{self.uuid}'

    def get_document_id(self):
        return self.invoice_number

    def get_mark_paid_url(self, entity_slug):
        return reverse('django_ledger:invoice-mark-paid',
                       kwargs={
                           'entity_slug': entity_slug,
                           'invoice_pk': self.uuid
                       })

    def get_migrate_state_desc(self):
        """
        Must be implemented.
        :return:
        """
        return f'Invoice {self.invoice_number} account adjustment.'

    def get_invoice_item_data(self, queryset=None) -> tuple:
        if not queryset:
            # pylint: disable=no-member
            queryset = self.itemthroughmodel_set.all().select_related('item_model')
        return queryset, queryset.aggregate(
            amount_due=Sum('total_amount'),
            total_items=Count('uuid')
        )

    def migrate_allowed(self) -> bool:
        return self.invoice_status == InvoiceModel.INVOICE_STATUS_APPROVED

    def get_item_data(self, entity_slug: str, queryset=None):
        if not queryset:
            # pylint: disable=no-member
            queryset = self.itemthroughmodel_set.all()
            queryset = queryset.filter(invoice_model__ledger__entity__slug__exact=entity_slug)
        return queryset.select_related('item_model').order_by('item_model__earnings_account__uuid',
                                                              'entity_unit__uuid',
                                                              'item_model__earnings_account__balance_type').values(
            'item_model__earnings_account__uuid',
            'item_model__earnings_account__balance_type',
            'item_model__cogs_account__uuid',
            'item_model__cogs_account__balance_type',
            'item_model__inventory_account__uuid',
            'item_model__inventory_account__balance_type',
            'item_model__inventory_received',
            'item_model__inventory_received_value',
            'entity_unit__slug',
            'entity_unit__uuid',
            'quantity',
            'total_amount').annotate(
            account_unit_total=Sum('total_amount'))

    def update_amount_due(self, queryset=None, item_list: list = None) -> None or tuple:
        if item_list:
            # self.amount_due = Decimal.from_float(round(sum(a.total_amount for a in item_list), 2))
            self.amount_due = sum(a.total_amount for a in item_list)
            return
        queryset, item_data = self.get_invoice_item_data(queryset=queryset)
        self.amount_due = item_data['amount_due']
        return queryset, item_data

    def is_approved(self):
        return self.invoice_status == self.INVOICE_STATUS_APPROVED

    def is_draft(self):
        return self.invoice_status == self.INVOICE_STATUS_DRAFT

    def can_edit_items(self):
        return self.is_draft()

    def can_update_items(self):
        return self.invoice_status not in [
            self.INVOICE_STATUS_APPROVED,
            self.INVOICE_STATUS_CANCELED
        ]

    def clean(self):
        if not self.invoice_number:
            self.invoice_number = generate_invoice_number()
        if self.is_draft():
            self.amount_paid = Decimal('0.00')
            self.paid = False
            self.paid_date = None
            self.progress = 0
        super().clean()


class InvoiceModel(InvoiceModelAbstract):
    """
    Base Invoice Model from Abstract.
    """

django_ledger/forms/account.py
from django.forms import TextInput, Select, ModelForm

from django_ledger.models.accounts import AccountModel
from django_ledger.settings import DJANGO_LEDGER_FORM_INPUT_CLASSES


class AccountModelCreateForm(ModelForm):
    def __init__(self, entity_slug, user_model, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ENTITY_SLUG = entity_slug
        self.USER_MODEL = user_model

    class Meta:
        model = AccountModel
        fields = [
            'code',
            'name',
            'role',
            'balance_type',
        ]
        widgets = {
            'code': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'name': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'role': Select(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'balance_type': Select(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
        }


class AccountModelCreateChildForm(AccountModelCreateForm):
    class Meta:
        model = AccountModel
        fields = [
            'code',
            'name',
            'balance_type',
        ]
        widgets = {
            'code': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'name': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'balance_type': Select(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
        }


class AccountModelUpdateForm(ModelForm):

    def __init__(self, entity_slug, user_model, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.ENTITY_SLUG = entity_slug
        self.USER_MODEL = user_model
        self.PARENT_ACCOUNT: AccountModel = self.instance.parent

        if self.PARENT_ACCOUNT:
            self.fields['parent'].queryset = AccountModel.on_coa.with_roles_available(
                entity_slug=self.ENTITY_SLUG,
                user_model=self.USER_MODEL,
                roles=[self.PARENT_ACCOUNT.role]
            )
        else:
            self.fields['parent'].queryset = AccountModel.on_coa.for_entity_available(
                user_model=self.USER_MODEL,
                entity_slug=self.ENTITY_SLUG,
            )

    class Meta:
        model = AccountModel
        fields = [
            'parent',
            'code',
            'name',
            'locked',
            'active'
        ]
        widgets = {
            'parent': Select(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'code': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
            'name': TextInput(attrs={
                'class': DJANGO_LEDGER_FORM_INPUT_CLASSES
            }),
        }

django_ledger/forms/app_filters.py
from django.forms import Form, ModelChoiceField, Select, ChoiceField, CharField, HiddenInput, DateField, DateInput
from django.utils.translation import gettext_lazy as _l

from django_ledger.models.entity import EntityModel
from django_ledger.models.journalentry import JournalEntryModel
from django_ledger.settings import DJANGO_LEDGER_FORM_INPUT_CLASSES


class EntityFilterForm(Form):
    entity_model = ModelChoiceField(
        queryset=EntityModel.objects.none(),
        widget=Select(attrs={
            'class': DJANGO_LEDGER_FORM_INPUT_CLASSES + ' djetler-set-entity-form-input',
        }))

    def __init__(self, *args, user_model, current_entity_uuid=None, form_id=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.USER_MODEL = user_model
        self.form_id = form_id
        self.fields['entity_model'].queryset = EntityModel.objects.for_user(
            user_model=self.USER_MODEL).only('slug', 'name')
        if form_id:
            self.fields['entity_model'].widget.attrs['class'] += f' djetler-default-entity-input-{self.form_id}'

        if current_entity_uuid:
            self.initial = {
                'entity_model': current_entity_uuid
            }


class ActivityFilterForm(Form):
    CHOICES = [('all', _l('All'))] + JournalEntryModel.ACTIVITIES
    activity = ChoiceField(choices=CHOICES,
                           label=_l('Activity'),
                           initial='all',
                           widget=Select(
                               attrs={
                                   'class': DJANGO_LEDGER_FORM_INPUT_CLASSES + ' is-small djetler-activity-select-form-input',
                               }
                           ))


class AsOfDateFilterForm(Form):

    def __init__(self, *args, form_id=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_id = form_id
        if form_id:
            self.fields['date'].widget.attrs['class'] += f' djetler-end-date-filter-input-{self.form_id}'

    entity_slug = CharField(
        max_length=150,
        widget=HiddenInput()
    )
    date = DateField(
        widget=DateInput(
            attrs={
                'class': 'is-hidden',
                'data-input': True,
            }
        ))

django_ledger/templates/django_ledger/includes/breadcrumbs.html
{% load django_ledger %}
<div class="container djetler_mt_1">
    <div class="columns">
        <div class="column">
            {% nav_breadcrumbs %}
        </div>
    </div>
</div>

django_ledger/templates/django_ledger/includes/card_customer.html
{% load i18n %}
{% load django_ledger %}

<div class="card">
    <div class="card-header">
        <h2 class="card-header-title has-text-weight-light is-size-3">
            <span class="icon is-large">
                    {% icon 'bi:person-lines-fill' 36 %}</span>
            {% trans 'Customer Information' %}</h2>
    </div>
    <div class="card-content">
        <div class="content">
            <h1 class="has-text-weight-bold">
                {{ customer.customer_name }}
            </h1>
            <p>
                {% if customer.address_1 %}{{ customer.address_1 }}<br>{% endif %}
                {% if customer.address_2 %}{{ customer.address_2 }}<br>{% endif %}
                {% if customer.get_cszc %}{{ customer.get_cszc }}<br>{% endif %}
                {% if customer.phone %}{{ customer.phone }}<br>{% endif %}
                {% if customer.email %}{{ customer.email }}<br>{% endif %}
                {% if customer.website %}{{ customer.website }}<br>{% endif %}
            </p>
        </div>
    </div>
    <footer class="card-footer">
        <a href="{% url 'django_ledger:customer-update' customer_pk=customer.uuid entity_slug=view.kwargs.entity_slug %}"
           class="card-footer-item has-text-primary has-text-centered">{% trans 'Edit' %}</a>
    </footer>

</div>

django_ledger/templates/django_ledger/includes/card_entity.html
{% load django_ledger %}
{% now "Y" as current_year %}

<div class="col-lg-3 col-md-6">
    <div class="iq-card dash-hover-gradient iq-card-block iq-card-stretch iq-card-height">
       <div class="iq-card-header d-flex justify-content-between border-0">
          <div class="mb-0 font-size-32 text-dark"><i class="ri-bank-line font-weight-light"></i></div>
          <div class="iq-card-header-toolbar d-flex align-items-center">
             <div class="dropdown">
                <span class="dropdown-toggle" id="d-28" data-toggle="dropdown">
                <i class="ri-more-2-fill "></i>
                </span>
                <div class="dropdown-menu dropdown-menu-right shadow-none">
                   <a class="dropdown-item" href="{{ entity.get_dashboard_url }}"><i class="ri-pencil-fill mr-2"></i>Dashboard</a>
                   <a class="dropdown-item" href="{{ entity.get_manage_url }}"><i class="ri-printer-fill mr-2"></i>Manage</a>
                   <a class="dropdown-item" href="{{ entity.get_delete_url }}"><i class="ri-delete-bin-6-fill mr-2"></i>Delete</a>
                </div>
             </div>
          </div>
       </div>
       <div class="iq-card-body">
          <h3><a href="{{ entity.get_dashboard_url }}">{{ entity.name }}</a></h3>
          <p class="mb-0">{{ entity.address_1 }}</p>
       </div>
       <div class="card-action font-size-14 p-3">
        Created : {{ entity.created | timesince }} ago
       </div>
    </div>
 </div>

django_ledger/templates/django_ledger/includes/card_invoice.html
{% load django_ledger %}
{% load i18n %}
{% if not create_invoice %}
{% if style == 'dashboard' %}

<div class="iq-card iq-card-block iq-card-stretch iq-card-height">
    <div class="iq-card-body">
        <div class="top-block d-flex align-items-center justify-content-between">
            <h5>{% trans 'Invoice' %}</h5>
            {% if not invoice.is_past_due %}
            <span class="badge badge-primary">Due in: {{ invoice.due_date | timeuntil }}</span>
        {% else %}
        <span class="badge badge-danger">Past
            Due: {{ invoice.due_date | timesince }} ago</span>
        {% endif %}
            
        </div>
        <h3 class="title">{{ invoice.customer.customer_name }}</h3>
        <p class="subtitle text-weight-light">{{ invoice.customer.address_1 }}</p>
        
        {% if invoice.accrue %}
        <p>Accrue: Accring
            {% else %}
            <p>Accrue:
                Not Accring 
                {% endif %}
                <p class="is-size-5 text-primary">Owed to You:
                    {% currency_symbol %}{{ invoice.get_amount_open | currency_format }}</p>
                <p>Amount Paid: {% currency_symbol %}{{ invoice.amount_paid | currency_format }}</p>
                <p>Progressed: {{ invoice.get_progress | percentage }}</p><br>
                {% comment %} <progress class="progress is-medium is-primary" value="{{ invoice.get_progress_percent }}"
                    max="100">{{ invoice.get_progress | percentage }}
                </progress> {% endcomment %}
                
                <div class="iq-progress-bar mt-3">
                    <span class="bg-primary" data-percent="{{ invoice.get_progress| percentage }}" style="transition: width 2s ease 0s; width: {{ invoice.get_progress| percentage }};"></span>
                 </div>
                 <br>
                {# MARK AS PAID MODAL #}
                {% modal_action invoice 'get' entity_slug %}

                <footer class="d-flex align-items-center justify-content-between">
                    <a href="{% url 'django_ledger:invoice-detail' entity_slug=entity_slug invoice_pk=invoice.uuid %}"
                        class="card-link">{% trans 'View' %}</a>
                    <a href="{% url 'django_ledger:invoice-update' entity_slug=entity_slug invoice_pk=invoice.uuid %}"
                        class="card-footer-item text-warning-dark text-centered">{% trans 'Update' %}</a>
                    {% if not invoice.paid %}
                    <a onclick="djLedger.toggleModal('{{ invoice.get_html_id }}')"
                        class="card-footer-item text-info text-centered">{% trans 'Mark as Paid' %}</a>
                    {% endif %}
                </footer>
            
    </div>
</div>


{% elif style == 'invoice-detail' %}
<div class="card">
    <div class="card-header">
        <h2 class="card-header-title text-weight-light is-size-3">
            <span class="icon is-large">
                {% icon 'uil:bill' 36 %}</span>
            {% trans 'Invoice Info' %}</h2>
    </div>
    <div class="card-content">

        {% if invoice.paid %}
        <p class="is-size-3 text-dark">Is Paid
            <span class="icon is-large text-primary-dark">
                {% icon 'ant-design:check-circle-filled' 48 %}
            </span>
        </p>
        <p class="is-size-4">Amount Paid:
            <span class="text-weight-bold">{% currency_symbol %}{{ invoice.amount_paid | currency_format }}</span>
        </p>
        {% else %}
        <p class="is-size-3 text-dark">Invoice Amount:
            <span class="text-weight-bold">{% currency_symbol %}{{ invoice.amount_due | currency_format }}</span>
        </p>
        <p class="is-size-4">Invoice Status: {{ invoice.get_invoice_status_display }}</p>
        {% if not invoice.is_past_due %}
        <p class="is-size-4 text-info">Due in: {{ invoice.due_date | timeuntil }}</p>
        {% else %}
        <p class="text-danger text-weight-bold is-size-3">Past
            Due: {{ invoice.due_date | timesince }} ago</p>
        {% endif %}
        <p class="is-size-5 text-primary">Owed to You:
            {% currency_symbol %}{{ invoice.get_amount_open | currency_format }}</p>

        {% if invoice.accrue %}
        <p>Accrue: <span class="icon text-primary">{% icon 'ant-design:check-circle-filled' 24 %}</span>
        </p>
        {% else %}
        <p>Accrue:
            <span class="icon is-small text-danger">{% icon 'maki:roadblock-11' 24 %}</span>
        </p>
        {% endif %}
        <p>Amount Paid: {% currency_symbol %}{{ invoice.amount_paid | currency_format }}</p>
        <p>Progressed: {{ invoice.get_progress_percent }}%</p><br>
        <progress class="progress is-medium is-primary" value="{{ invoice.get_progress_percent }}" max="100">
            {{ invoice.get_progress | percentage }}
        </progress>

        {% endif %}

        {# MARK AS PAID MODAL #}
        {% modal_action invoice 'get' entity_slug %}

    </div>
    <footer class="card-footer">
        <a href="{% url 'django_ledger:invoice-update' entity_slug=entity_slug invoice_pk=invoice.uuid %}"
            class="card-link">{% trans 'Update' %}</a>
        {% if not invoice.paid %}
        <a onclick="djLedger.toggleModal('{{ invoice.get_html_id }}')"
            class="card-footer-item text-info text-centered">{% trans 'Mark as Paid' %}</a>
        {% endif %}
        <a href="{% url 'django_ledger:invoice-delete' entity_slug=entity_slug invoice_pk=invoice.uuid %}"
            class="card-footer-item text-danger text-centered">{% trans 'Delete' %}</a>
    </footer>
</div>

{% endif %}
{% else %}
<div class="box text-centered">
    <a href="{% url 'django_ledger:invoice-create' entity_slug=entity_slug %}">
        <h2 class="is-size-3 text-grey">{% trans 'New Invoice' %}</h2>
    </a>
</div>
{% endif %}

django_ledger/templates/django_ledger/includes/card_markdown.html
{% load trans from i18n %}
{% load django_ledger %}

{% if style == 'card_1' %}
    <div class="card">
        <div class="card-header">
            <div class="card-header-title">
                <h1 class="is-size-3 has-text-weight-light">{% if title %}{{ title }}{% else %}
                    {% trans 'Notes' %}
                {% endif %}</h1>
            </div>
        </div>
        <div class="card-content">
            <div class="content">
                {% if notes_html %}
                    {% autoescape off %}
                        {{ notes_html | safe }}
                    {% endautoescape %}
                {% else %}
                    <p>{% trans 'No available notes to display...' %}</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endif %}

django_ledger/templates/django_ledger/includes/card_po.html
{% load i18n %}
{% load django_ledger %}

{% if not create_po %}
    {% if style == 'po-detail' %}
        <div class="card">
            <div class="card-header">
                <h2 class="card-header-title has-text-weight-light is-size-3">
            <span class="icon is-large">
                    {% icon 'uil:bill' 36 %}</span>
                    {% trans 'Purchase Order Info' %}</h2>
            </div>
            <div class="card-content">
                <h2 class="is-size-3">{{ po_model.po_number }}</h2>
                <h3 class="is-size-4 has-text-weight-light">
                    Status: <span
                        class="{% if po_model.po_status == 'draft' %}has-text-danger{% elif po_model.po_status == 'approved' %}has-text-success{% endif %}">
                    {{ po_model.get_po_status_display }}</span></h3>
                <h3 class="is-size-4 has-text-weight-light">Inventory Purchase:
                    {% if po_model.for_inventory %}
                        <span class="icon has-text-success">{% icon 'ant-design:check-circle-filled' 24 %}</span>
                    {% else %}
                        <span class="icon is-small has-text-danger">{% icon 'maki:roadblock-11' 24 %}</span>
                    {% endif %}
                </h3>
                <h3 class="is-size-4 has-text-weight-light">Fulfilled:
                    {% if po_model.fulfilled %}
                        <span class="icon has-text-success">{% icon 'ant-design:check-circle-filled' 24 %}</span>
                        {{ po_model.fulfillment_date | date }}
                    {% else %}
                        <span class="icon is-small has-text-danger">{% icon 'maki:roadblock-11' 24 %}</span>
                    {% endif %}
                </h3>

            </div>

            <footer class="card-footer">
                <a href="{% url 'django_ledger:po-update' entity_slug=entity_slug po_pk=po_model.uuid %}"
                   class="card-footer-item has-text-primary has-text-centered">{% trans 'Update' %}</a>
                {% if po_model.can_mark_as_fulfilled %}
                    <a onclick="djLedger.toggleModal('{{ po_model.get_html_id }}')"
                       class="card-footer-item has-text-info has-text-centered">{% trans 'Mark as Fulfilled' %}</a>
                {% endif %}
                <a href="{% url 'django_ledger:po-delete' entity_slug=entity_slug po_pk=po_model.uuid %}"
                   class="card-footer-item has-text-danger has-text-centered">{% trans 'Delete' %}</a>
            </footer>

        </div>

    {% endif %}
{% else %}
    <div class="box has-text-centered">
        <a href="{% url 'django_ledger:po-create' entity_slug=entity_slug %}">
            <span class="icon is-large has-text-grey">{% icon "ic:baseline-add-circle-outline" 48 %}</span></a>
        <h2 class="is-size-3 has-text-grey">{% trans 'New PO' %}</h2>
    </div>
{% endif %}

django_ledger/templates/django_ledger/includes/messages.html
{% if messages %}
    {# Messages Container #}
    <div class="container px-2">
        {% for msg in messages %}
            <div class="notification {{ msg.tags }} mt-3 mb-2">
                <button class="delete"></button>
                {{ msg | safe }}
            </div>
        {% endfor %}
    </div>
{% endif %}